# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e6bbd9e9f96cefd9e3f605253ed3d54d11d5525eb52aeda1053874dd1c9d650ddd4e018a7a081b56099d45dbbbca28e8d48daae1e066ac7f688f6c0f7649b29

test:
  secret_key_base: ad6f43b9e05c6ccbc7f0d494053a77732ac6cb8e3e7796b4eb42a6b444e99d4e4c132aac12185376eead5e83a1c940098bacf11b7892451a78f337375b6dac10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
